# Generated by Django 5.0.4 on 2024-05-11 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=127)),
                ('descricao', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('steam_id', models.IntegerField()),
                ('totalPontos', models.IntegerField(default=0)),
                ('numeroRatings', models.IntegerField(default=0)),
                ('media', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListaUtilizadorJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CM', 'Completed'), ('PP', 'Plan To Play'), ('DR', 'Dropped'), ('PL', 'Playing'), ('OH', 'On Hold')], default='PP', max_length=2)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_altered', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagem', models.IntegerField(default=0)),
                ('listaUtilizadorJogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listautilizadorjogo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaGameplays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.gameplay')),
                ('listaUtilizadorJogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listautilizadorjogo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=511)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipoReview', models.CharField(choices=[('MF', 'Mixed Feelings'), ('RC', 'Recommended'), ('DR', 'Not Recommended')], max_length=2)),
                ('listaUtilizadorJogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listautilizadorjogo')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=127)),
                ('descricao', models.CharField(max_length=511)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('threadTopic', models.CharField(choices=[('GB', 'Game Build'), ('SG', 'Strategy'), ('CP', 'Competitive'), ('MO', 'Modding'), ('CO', 'Completion'), ('GU', 'Game Updates'), ('GE', 'Game Events'), ('LO', 'Lore'), ('ST', 'Soundtrack'), ('GR', 'Graphics'), ('GM', 'Game Mechanics'), ('EE', 'Easter Eggs'), ('OT', 'Other')], default='OT', max_length=2)),
                ('listaThreads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listathreads')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('genero', models.CharField(default='Not Specified', max_length=50)),
                ('biografia', models.CharField(max_length=255)),
                ('localidade', models.CharField(max_length=100)),
                ('jogos_completos', models.IntegerField(default=0)),
                ('profile_picture', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listautilizadorjogo',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.utilizador'),
        ),
        migrations.CreateModel(
            name='Lista_Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_id', to='gameapp.utilizador')),
                ('utilizador_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_seguido_id', to='gameapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='LinksUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=127)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.thread')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.utilizador')),
            ],
        ),
    ]
