# Generated by Django 5.0.4 on 2024-04-29 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=127)),
                ('descricao', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('steam_id', models.IntegerField()),
                ('totalPontos', models.IntegerField(default=0)),
                ('numeroRatings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListaUtilizadorJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CM', 'Completed'), ('PP', 'Plan To Play'), ('DR', 'Dropped'), ('PL', 'Playing'), ('OH', 'On Hold')], default='PP', max_length=2)),
                ('rating', models.IntegerField(default=0)),
                ('jogo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaGameplays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.gameplay')),
                ('listaUtliziadorJogo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listautilizadorjogo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=127)),
                ('texto', models.CharField(max_length=511)),
                ('listaUtliziadorJogo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameapp.listautilizadorjogo')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=255)),
                ('localidade', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listautilizadorjogo',
            name='utilizador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.utilizador'),
        ),
        migrations.CreateModel(
            name='Lista_Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_id', to='gameapp.utilizador')),
                ('utilizador_seguido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_seguido_id', to='gameapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='LinksUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=127)),
                ('utilizador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.utilizador')),
            ],
        ),
    ]
