# Generated by Django 5.0.4 on 2024-05-05 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_listautilizadorjogo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_amigos',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
