# Generated by Django 5.0.4 on 2024-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_gameplay_created_at_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listautilizadorjogo',
            name='last_altered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
