# Generated by Django 5.0.4 on 2024-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_review_tiporeview_review_updated_thread_threadtopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='titulo',
        ),
    ]
